"""OC-009/OC-013/OC-014 — LLM client (OpenAI-compat, talks to llama-server).

Two modes:
  - live: talks to llama-server at OPENCLAW_LLM_BASE_URL.
  - stub: deterministic local responder, used for tests and the AFK proving slice
    when no llama-server is up. Stub responses are clearly marked in the audit
    trace so they cannot be confused with live output.
"""
from __future__ import annotations
import hashlib
import json
import textwrap
from typing import Any
import httpx
from .config import get_settings


class LLMError(Exception):
    pass


class LLMClient:
    def __init__(self, settings=None):
        self.s = settings or get_settings()

    @property
    def mode(self) -> str:
        return self.s.OPENCLAW_LLM_MODE.lower()

    def chat(self, system: str, user: str, *, max_tokens: int = 1024,
             temperature: float = 0.2) -> dict[str, Any]:
        if self.mode == "stub":
            return self._stub_chat(system, user)
        return self._live_chat(system, user, max_tokens=max_tokens, temperature=temperature)

    def _live_chat(self, system: str, user: str, *, max_tokens: int,
                   temperature: float) -> dict[str, Any]:
        url = f"{self.s.OPENCLAW_LLM_BASE_URL.rstrip('/')}/chat/completions"
        payload = {
            "model": self.s.OPENCLAW_LLM_MODEL,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "max_tokens": max_tokens,
            "temperature": temperature,
        }
        headers = {"Authorization": f"Bearer {self.s.OPENCLAW_LLM_API_KEY}"}
        try:
            r = httpx.post(url, json=payload, headers=headers, timeout=120)
            r.raise_for_status()
        except httpx.HTTPError as e:
            raise LLMError(f"llama-server chat call failed: {e}") from e
        data = r.json()
        msg = data["choices"][0]["message"]["content"]
        return {
            "mode": "live",
            "model": self.s.OPENCLAW_LLM_MODEL,
            "content": msg,
            "raw": data,
        }

    def _stub_chat(self, system: str, user: str) -> dict[str, Any]:
        """Deterministic responder. Inspects the system prompt to pick a template."""
        sig = hashlib.sha256((system + user).encode()).hexdigest()[:12]
        sys_l = system.lower()

        if "implementer" in sys_l or "deck outline" in sys_l:
            content = self._stub_deck_outline(user, sig)
        elif "reviewer" in sys_l:
            content = self._stub_review(user, sig)
        else:
            content = f"[stub] sig={sig}\n\nReceived task; no template matched."

        return {
            "mode": "stub",
            "model": "stub:deterministic",
            "content": content,
            "raw": {"signature": sig},
        }

    @staticmethod
    def _stub_deck_outline(user: str, sig: str) -> str:
        # Prefer an explicit TASK_TITLE: line if the caller provided one.
        title_hint = "Strategic Readout"
        for line in user.splitlines():
            if line.startswith("TASK_TITLE:"):
                title_hint = line.split(":", 1)[1].strip()[:80]
                break
        return textwrap.dedent(f"""\
            # Board Readout — {title_hint}

            > Generated by stub LLM (sig {sig}). Replace with live model in production.

            ## Slide 1 — Context
            - Why we are here today
            - Recent client developments worth flagging
            - **Speaker note:** Open with the headline event; anchor in business impact, not tech.

            ## Slide 2 — What changed
            - The triggering event and its operational implications
            - Stakeholders most affected
            - **Speaker note:** Quantify exposure where possible; if not, name the dependency.

            ## Slide 3 — Options on the table
            - Option A: hold
            - Option B: accelerate
            - Option C: pivot scope
            - **Speaker note:** Present trade-offs in dollars, time, and risk — in that order.

            ## Slide 4 — Visionet recommendation
            - Recommended path with rationale
            - 30/60/90 view
            - **Speaker note:** Lead with the recommendation; reasons follow only if challenged.

            ## Slide 5 — Asks
            - Decisions needed today
            - Resources required
            - **Speaker note:** Close with a single, named next action and an owner.
            """)

    @staticmethod
    def _stub_review(user: str, sig: str) -> str:
        return json.dumps({
            "verdict": "needs-revisions",
            "signature": sig,
            "suggestions": [
                {
                    "slide": 1,
                    "issue": "Context slide does not name the specific event date.",
                    "fix": "Insert event date in Slide 1 bullet 2.",
                    "severity": "minor",
                },
                {
                    "slide": 4,
                    "issue": "Recommendation lacks a quantified upside.",
                    "fix": "Add a one-line dollar or time-savings estimate to the recommendation bullet.",
                    "severity": "major",
                },
                {
                    "slide": 5,
                    "issue": "Asks slide should name a single owner per decision.",
                    "fix": "Append '(owner: <name>)' to each ask bullet.",
                    "severity": "minor",
                },
            ],
        }, indent=2)
